language: node_js
node_js:
  - '8'
install:
  - npm install
script:
  - npm run coverage
  - npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: martin.gabel@icechair.de
  on:
    tags: true
  api_key:
    secure: SwxnDpQEu+nxUB8S6JU3ssd7mPUZjlGKlATu3CnqH6gDO+J3TL/52oXRGdn3QXW/R6diMgnLHfJKJ6bXbHdeIED8U262p0AIZIEhORSTPuFCnWMXvzCGPvqjrDvgCwLPtpBCVYKs0qXsE+Wd1WFFjy/elzCHzJoMu6sCHD0u5evKZeem/rwRUL7pr7Cm/2ZJJBybcTDLUs+RP8KyQpmKJzgPtmdDbjWBqmtW2sU3RnCgMe7hIqL/OYeptWaumSEef9MyiE/TRR2LZAAIb4tDN+reEOfl1wv5WSlLBRKaxx/jRcN7SD6f31L0wIaUz9xdqV93HQ/74gKVZOO1vdqdBzY3qnMROzT25z6nBew80D3Kba1xdrjWrw06OtyB7BhO/5agjZ5IHSd1ZiFI2OQlBc/NqyZMH5ebYu7UzaheJexYiOmxwUI9wp/zVzH1wQtR12I7A64Tnmz1LELvZNyTS0Gb6WovjCdE0NoUzdlUqtUzmrtoVWHoYx9NXro5AeN+4g+voQFSMmHof+dRb+gffRgNJpD924dez26Q4X7UpKZ0NXoqvTYIYB7qZ4PYahARk5GuTNUv8Z3l5eNYVf5tofMWSAOdg0EaKUBMP4sIP8rpXJwrtvsgEQy9dLcZCsGemM9CqIQHfAijuegmwpiLL8+zDhvY64D4u2ZnCaxjT+c=
